---
dist: xenial

env:
  global:
    - DOCKER_CONTAINER=frankjoshua/ros-jviz
  matrix:
    - DOCKER_ARCH: 'linux/arm/v7'
    - DOCKER_ARCH: 'linux/arm64/v8'
    - DOCKER_ARCH: 'linux/amd64'

before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start

script:
  - while sleep 15s; do echo "=====[ $SECONDS seconds, buildroot still building... ]====="; done &
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - time ./build.sh -t $DOCKER_CONTAINER -a $DOCKER_ARCH -q
  # Killing background sleep loop
  - kill %1
